### ISSUE TITLE
IOs support

### ISSUE THREAD

**Issue by ChrisHoffmann96** [DevelopGadget/flutter_adcolony#1]
Thank you for the plugin! Do you know when the IOs support will be ready?

**Comment by DevFx16** [comment]
It's uncertain friend, but we hope and be soon

**Comment by davidcantonnadales** [comment]
Hello friend, thanks for the plugin, please, do it for iOS, you can contact with me if you prefer do this improvement as freelance, i am interested in pay you for the iOS version
