### ISSUE TITLE
Lost connection to device.

### ISSUE THREAD

**Issue by anindyacode** [DevelopGadget/flutter_adcolony#3]
Installing startapp package on pubspec.yaml succed but in Run time, it makes error :

Syncing files to device AOSP on IA Emulator...
Lost connection to device.
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:51035/W7Z6QnRIcuo=/ 

When I erased startapp package on pubspec.yaml, in Run time, the error disappeared.

**Comment by DevFx16** [comment]
the error is not from the package
