### ISSUE TITLE
Banners now work a little ;)

### ISSUE THREAD

**Issue by reijpower** [DevelopGadget/flutter_adcolony#8]
Hi again,

thanks for fixing the issue, but now I get a "onRequestNotFilled" error for the banners,
after some research some guy on stackoverflow posted to a releated issue: "Either onRequestFilled is not being called or it is being called after onCreate - add some logging to get an idea of the timing and then put something in place to force things to line up as you intend"

Greetings

**Comment by abozanona** [comment]
Hi @reijpower 
Could you please explain how did you fix this issue?

**Comment by DevFx16** [comment]
Fix in 2.0.6
